from manimlib.imports import *

class MathematicalInduction(Scene):
    def construct(self):

        t1=TextMobject("Mathematical  Induction",font='Times New Roman',color="#39C5BB").scale(2.3).shift(UP)
        self.play(Write(t1))
        self.wait(1)
        t2=TexMobject("Made\,\,by\,\,Erikpsw",color="#66CCFF").next_to(t1,DOWN).shift(2*RIGHT)
        self.play(ShowCreation(t2))
        self.wait(1)
        G1=VGroup(t1,t2)
        self.play(Uncreate(G1))
        self.wait(1)
        t3=TexMobject(r"\sum_{i = 1}^{k} i ^ {2} = \frac{k {(k + 1)} {(2 k + 1)}}{6}")
        self.play(ShowCreation(t3))
        self.wait(1)
        self.play(ApplyMethod(t3.shift, UP * 3))
        self.wait(1)
        t7=TexMobject(r"\sum_{i = 1}^{k+1}i^{2}&= \sum_{i = 1}^{k} i ^ {2}+(k+1)^2\\&= \frac{k {(k + 1)} {(2 k + 1)+6(k+1)^2}}{6}\\&=\frac{(k + 1)(2k^2+7k+6)}{6}\\&=\frac{(k + 1)[(k+1)+1][2(k+1)+1]}{6}").next_to(t3,DOWN)
        self.play(ShowCreation(t7))
        self.wait(3)
        G2 = VGroup(t3, t7)
        t5=TexMobject(r"t=(1+x)^n-1\rightarrow0")
        self.play(ReplacementTransform(G2,t5))
        self.wait(1)
        self.play(ApplyMethod(t5.shift, UP*3))
        t4 = TexMobject(r'''
        \lim_{x \to 0} \frac{(1+x)^n-1}{x}(n\in R)&=\lim_{x \to 0}[\frac{(1+x)^n-1}{\ln(1+x)^n}\cdot\frac{n\ln(1+x)}{x}]\\&=\lim_{x \to 0} \frac{t}{\ln(1+t)}\cdot\lim_{x \to 0}\frac{n\ln(1+x)}{x}\\&=\frac 1 e\cdot e\cdot n\\&=n''').next_to(
            t5, DOWN)
        t6 = TexMobject(r"(1+x)^\alpha\thicksim 1+\alpha x(x\rightarrow0)").next_to(t4, DOWN)
        self.wait(1)
        self.play(Write(t4))
        self.wait(1)
        self.play(Write(t6))
        self.wait(2)
        G3=VGroup(t4,t5,t6)
        self.play(FadeOutAndShift(G3,LEFT))
        self.wait(1)
        t8=TexMobject(r"(1+x)^n> 1+n x\;(n>1,n\in N^*)").shift(UP*3)
        self.play(FadeInFrom(t8,BOTTOM))
        t9=TexMobject(r"( 1 + x ) ^ { k } > 1 + k x").next_to(t8,DOWN).shift(0.5*DOWN)
        t10=TexMobject(r"( 1 + x ) ^ { k + 1 } &= ( 1 + x ) ( 1 + x ) ^ { k } \\&>{ ( 1 + x ) ( 1 + k x ) }\\ &={ 1 + x + k x + k x ^ { 2 } }\\ &> {1 + ( k + 1 ) x }").next_to(t9,DOWN)
        self.wait(1)
        self.play(ShowCreation(t9))
        self.wait(1)
        self.play(FadeInFromLarge(t10,2))
        self.wait(3)
        G4=VGroup(t8,t9,t10)
        self.play(Uncreate(G4))
        self.wait(1)
        t11=TextMobject("Thanks",font='Times New Roman').scale(3)
        t12=TextMobject("2020年12月20日",font='华文中宋').next_to(t11,DOWN).shift(RIGHT)
        self.play(Write(t11))
        self.play(Write(t12))
        self.wait(2)


